spring:
  application:
    name: fco-demo
  cloud:
    config:
      profile: production
      uri: http://localhost:8888
      fail-fast: true
  devtools:
    livereload:
      port: 35730
debug: true
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"